### ISSUE TITLE
Add Sam to this organization 

### ISSUE THREAD

**Issue by HomelessDev** [DiscordFa/DiscordFa#1]
Sam isn't member of this organization

**Comment by OstadHamid** [comment]
sadge

**Comment by OstadHamid** [comment]
> Sam isn't member of this organization

Sadge

**Comment by ItzRsam** [comment]
> > Sam isn't member of this organization
> 
> Sadge
https://media.discordapp.net/attachments/844224424030240808/861192062410162192/854385789106520064.gif

**Comment by VelterZI** [comment]
:)

**Comment by HomelessDev** [comment]
> :)

: |
